### ISSUE TITLE
Run test failed on loongarch

### ISSUE THREAD

**Issue by yetist** [gimli-rs/object#436]
@xry111 @zhaixiaojuan 

I run the command `cargo test` on loongarch64, and the test failed:

```
running 8 tests
test pod::tests::single ... ok
test pod::tests::slice ... ok
test read::archive::tests::bsd_names ... ok
test read::archive::tests::gnu_names ... ok
test read::archive::tests::kind ... ok
test read::coff::section::tests::name_offset ... ok
test read::util::tests::bytes ... ok
test read::util::tests::bytes_debug ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration.rs (target/debug/deps/integration-67b2eb25dd2432a1)

running 1 test
test read::coff::coff_extended_relocations ... FAILED

failures:

---- read::coff::coff_extended_relocations stdout ----
thread 'read::coff::coff_extended_relocations' panicked at 'Could not read relocs_overflow.o: Os { code: 2, kind: NotFound, message: "No such file or directory" }', tests/read/coff.rs:9:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    read::coff::coff_extended_relocations

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by xry111** [comment]
Try `git submodule init; git submodule update`.  `relocs_overflow.o` belongs to a submodule.

**Comment by xry111** [comment]
But I've not written code paths for COFF: there is no LoongArch COFF ABI drafted so we can't expect any COFF support on LoongArch anyway.  `relocs_overflow.o` is an Intel 80386 COFF file.

**Comment by yetist** [comment]
> Try `git submodule init; git submodule update`. `relocs_overflow.o` belongs to a submodule.

Sorry, I forgot to sync the git submodule. After doing it, I get the new test failed:
```
File testfiles/wasm/base.wasm                                                    
Test crates/examples/testfiles/wasm/base.wasm.objdump                            
FAIL mismatch                                                                    
FAIL unexpected stderr                                                           
                                                                                 
thread 'testfiles' panicked at 'assertion failed: !fail', crates/examples/tests/testfiles.rs:37:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace    
                                                                                 
                                                                                 
failures:                                                                        
    testfiles                                                                    
```

Maybe this bug is related to LLVM?
```
$ llvm-config --targets-built
AArch64 AMDGPU ARM AVR BPF Hexagon Lanai LoongArch Mips MSP430 NVPTX PowerPC RISCV Sparc SystemZ WebAssembly X86 XCore
```

**Comment by philipc** [comment]
I think that one needs `--feature wasm` to pass. That's probably something that should be fixed.

**Comment by xry111** [comment]
> I think that one needs `--feature wasm` to pass. That's probably something that should be fixed.

I can confirm adding `--features=wasm` makes the test to pass (on AMD64 and LoongArch).

**Comment by yetist** [comment]
I added `--features wasm`, all test cases passed.
