### ISSUE TITLE
Panic while writing Mach-O file

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/object#552]
```rust
fn main() {
    let mut obj = object::write::Object::new(
        object::BinaryFormat::MachO,
        object::Architecture::X86_64,
        object::Endianness::Little,
    );

    let sect = obj.add_section(vec![], vec![], object::SectionKind::ReadOnlyDataWithRel);
    obj.append_section_data(sect, &vec![0u8; 32], 8);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::ReadOnlyData);
    obj.append_section_data(sect, &vec![0u8; 1], 32);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Text);
    obj.append_section_data(sect, &vec![0u8; 1], 8);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Debug);
    obj.append_section_data(sect, &vec![0u8; 1], 1);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Debug);
    obj.append_section_data(sect, &vec![0u8; 1], 1);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Debug);
    obj.append_section_data(sect, &vec![0u8; 1], 1);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Debug);
    obj.append_section_data(sect, &vec![0u8; 1], 1);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::Debug);
    obj.append_section_data(sect, &vec![0u8; 1], 1);

    let sect = obj.add_section(vec![], vec![], object::SectionKind::ReadOnlyData);
    obj.append_section_data(sect, &vec![0u8; 1688], 8);

    obj.write().unwrap();
}
```

panics with

```
thread 'main' panicked at 'assertion failed: segment_file_size as u64 <= address', /home/bjorn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.31.1/src/write/macho.rs:338:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: object::write::macho::<impl object::write::Object>::macho_write
             at /home/bjorn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.31.1/src/write/macho.rs:338:9
   4: object::write::Object::emit
             at /home/bjorn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.31.1/src/write/mod.rs:593:36
   5: object::write::Object::write
             at /home/bjorn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.31.1/src/write/mod.rs:566:9
   6: foo::main
             at ./src/main.rs:35:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

cc https://github.com/bjorn3/rustc_codegen_cranelift/issues/1377

**Comment by philipc** [comment]
The problem is that after the first section, the file offset is not aligned to 32, but the address is aligned to 32. For the section section, this results in alignment padding for the file, but not for the address. I'll need to investigate further to determine if this assert is correct, and if so, what the fix is.
